// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package shuffletui

import (
	"database/sql"
)

type Session struct {
	Sshkey   []byte
	Username string
	Apikey   sql.NullString
}
